site:
  name: Tuxibot
  site: 'https://tuxibot.com' # Your actual domain
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata optimized for AI document search
metadata:
  title:
    default: Tuxibot - AI-Powered Document Search
    template: '%s | Tuxibot'
  description: "🔍 Intelligent document search powered by AI. Find answers instantly across your documents, PDFs, and knowledge base with advanced semantic search capabilities."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Tuxibot
    images:
      - url: '~/assets/images/tuxibot-og-image.png' # Create a custom OG image
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@tuxibot' # Update with your Twitter handle
    site: '@tuxibot'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 8 # Increased for better content discovery

    post:
      isEnabled: true
      permalink: '/insights/%slug%' # Changed to "insights" for AI/tech focus
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'insights' # Changed from "blog" to "insights"
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'topics' # More relevant for document search categories
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tags' # Keep tags for search optimization
      robots:
        index: true # Enable indexing for better discoverability

    isRelatedPostsEnabled: true
    relatedPostsCount: 6 # Increased for better content discovery

analytics:
  vendors:
    googleAnalytics:
      id: null # Add your GA4 ID: "G-XXXXXXXXXX"

ui:
  theme: 'dark:only' # Allow users to choose light/dark for better UX

# Additional SEO optimization for AI/search focus
search:
  enabled: true
  provider: 'pagefind' # Enable built-in search
  
# Custom metadata for AI document search branding
branding:
  tagline: "AI-Powered Document Intelligence"
  keywords: 
    - "AI document search"
    - "semantic search"
    - "document intelligence"
    - "knowledge management"
    - "AI-powered search"
    - "document analysis"
    - "intelligent search"